import "./globals.css"
import Useclient from "./component/UseClient"
import Head from "next/headt"
const inter = inter({ subsets: ["latin"] })

export const metadata = {
  title: "Gloria",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Gloria</title>
      </Head>
      <body className={inter.className}>
        {children}
        <Useclient />
      </body>
    </html>
  )
}
